# Development Dockerfile for WWT git-foundations

FROM python:3.9-slim-buster

LABEL maintainer="Tim Hull <tim.hull@wwt.com>" \
      version='1.0.5'


# TCP 8000 for MkDocs server
EXPOSE 8000/tcp

# Update repositories and install Git
RUN apt-get update && \
    apt-get install -y git

# Copy requirements files to Image
COPY requirements/ /requirements

# Install Python packages
RUN python -m pip install --upgrade pip && \
    python -m pip install -r ./requirements/requirements.txt && \
    rm -rf ./requirements

CMD ["/bin/bash"]
