---
# This action performs a lint of markdown files in the repository

# Name of the action
name: Markdown Linting

# Events which trigger the action
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  markdownlint:
    name: Lint markdown (.md) files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: .markdownlint.json
